videos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = "videos"
urlpatterns = [
  path("", views.MediaIndex.as_view(), name="medialist"),
  path("recent", views.MediaListIndex.as_view(), name="recentlist"),
  path("featured", views.MediaFeaturedList.as_view(), name="featured"),
  path("upload", views.UploadFormView.as_view(), name="upload"),
  path("submit-upload", views.UploadView.as_view(), name="submitupload"),
  path('upload-chunk', login_required(views.TestResumableView.as_view()), name='uploadchunk'),
  path("play/<uuid:uuid_code>", views.WatchView.as_view(), name="watch"),
  path("category/<slug:slug>", views.CategoryView.as_view(), name="category"),
  path("tag/<slug:slug>", views.MediaTaggedList.as_view(), name="tagged"),
  path("top-uploads", views.TopMediaList.as_view(), name="topmedia"),
  path("popular/<str:period>", views.PopularMediaList.as_view(), name="popular"),
  path("feed/history", login_required(views.MediaHistoryList.as_view()), name="playhistory"),
  path("playlist/<slug:slug>", login_required(views.MediaPlaylistView.as_view()), name="playlist"),
  path("subscriptions", login_required(views.MediaSubscriptionChannelView.as_view()), name="subscriptions"),
  path("subscriptions/latest", login_required(views.MediaSubscriptionMediaView.as_view()), name="subscribemedia"),
  path("channel/<slug:slug>", views.ChannelView.as_view(), name="channel"),
  path("search/", views.MediaSearchView.as_view(), name="search"),
  path("reaction/<int:id>", views.MediaReactionChange.as_view(), name="changereaction"),
  path("toggle-subscription/<int:id>", views.ToggleSubscription.as_view(), name="togglesub"),
]

videos/models.py
import datetime
import uuid
import os
import re

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.utils.safestring import mark_safe
from sorl.thumbnail import ImageField
from taggit.managers import TaggableManager
#from reacts.models import Reaction

from .storage import FileMoveSystemStorage

re_timestamptext = re.compile(r"(\d{2}:)?(\d{1,2})?:(\d{2})")

# Create your models here.

def thumbnail_user_upload_to(instance, filename):
  current_date = datetime.datetime.now()
  uuid_code = instance.uuid_code.hex
  username = instance.uploader.username.lower()
  file_ext = os.path.splitext(filename)[1]
  return "media_uploads/{}/{}/{}/thumbs/{}{}".format(username, current_date.year, current_date.strftime("%m"), uuid_code, file_ext)

def tmp_media_upload_to(instance, filename):
  current_date = datetime.datetime.now()
  uuid_code = instance.uuid_code.hex
  username = instance.uploader.username.lower()
  file_ext = os.path.splitext(filename)[1]
  return "media_uploads/{}/{}/{}/{}{}".format(username, current_date.year, current_date.strftime("%m"), uuid_code, file_ext)

def default_media_cat():
  return MediaCategory.objects.only("id").get_or_create(id=1, slug="other", defaults={"title": "Other"})[0].id


class MediaCategory(models.Model):
  title = models.CharField(max_length=50, unique=True)
  slug = models.SlugField()
  summary = models.CharField(max_length=200, blank=True)
  description = models.TextField(blank=True)

  def __str__(self):
    return self.title

  class Meta(object):
    verbose_name_plural = "Media Categories"

  def get_absolute_url(self):
    return reverse("videos:category", args=(self.slug,))


class PublishedMediaManager(models.Manager):
  def get_queryset(self):
    return super().get_queryset().filter(status=Media.PUBLISHED,
visibility=Media.PUBLIC)


class Media(models.Model):
  PENDING = 0
  PROCESSING = 1
  PUBLISHED = 2
  ERROR = 3

  MEDIA_STATE = (
    (PENDING, "Pending"),
    (PROCESSING, "Processing"),
    (PUBLISHED, "Published"),
    (ERROR, "Error"),
  )

  UNPUBLISHED = 0
  PUBLIC = 1
  UNLISTED = 2
  PRIVATE = 3

  PUBLISHED_STATUS = (
    (UNPUBLISHED, "Unpublished"),
    (PUBLIC, "Public"),
    (UNLISTED, "Unlisted"),
    (PRIVATE, "Private"),
  )

  ALL_AGES = 0
  NSFW = 1
  NSFL = 2
  RATING_CHOICES = (
    (ALL_AGES, "All Ages"),
    (NSFW, "NSFW"),
    (NSFL, "NSFL"),
  )

  title = models.CharField(max_length=100)
  slug = models.SlugField()
  uuid_code = models.UUIDField(default=uuid.uuid4, editable=False, db_index=True)
  media_file = models.FileField(upload_to=tmp_media_upload_to, max_length=200, storage=FileMoveSystemStorage(location=settings.TMP_UPLOAD_ROOT))
  description = models.TextField(blank=True)
  uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, default=None)
  view_count = models.IntegerField(default=0, db_index=True)
  creation_date = models.DateTimeField(default=timezone.now)
  updated_date = models.DateTimeField(default=timezone.now)
  category = models.ForeignKey(MediaCategory, on_delete=models.CASCADE,
default=default_media_cat)
  thumbnail = ImageField(upload_to=thumbnail_user_upload_to, max_length=200)
  status = models.IntegerField(default=0, choices=MEDIA_STATE)
  visibility = models.IntegerField(default=0, choices=PUBLISHED_STATUS)
  rating = models.IntegerField(default=ALL_AGES, choices=RATING_CHOICES)
  publish_date = models.DateTimeField(default=timezone.now)
  # Rename to duration
  duration = models.IntegerField(default=0)
  #file_size = models.PositiveIntegerField(default=0)
  #reacts = GenericRelation(Reaction, related_query_name="reactions")

  objects = models.Manager() # The default manager
  public_objects = PublishedMediaManager()
  tags = TaggableManager(blank=True, help_text="Up to three space-separated list of tags")

  def __str__(self):
    return self.title

  class Meta(object):
    verbose_name = "Media File"
    verbose_name_plural = "Media Files"
    ordering = ["-id"]
    #indexes = [
    #  models.Index(fields=['status', 'visibility'], name="Main Listing"),
    #]

  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = slugify(self.title)[:50]

    self.updated_date = timezone.now()
    super().save(*args, **kwargs)

  def get_absolute_url(self):
    return reverse("videos:watch", args=(self.uuid_code,))

  def get_admin_url(self):
    return reverse("admin:{}_{}_change".format(self._meta.app_label, self._meta.model_name), args=(self.id,))

  @property
  def is_public(self):
    return (self.status == self.__class__.PUBLISHED and
self.visibility == self.__class__.PUBLIC)

  @property
  def public_view_count(self):
    current = self.view_count
    if self.view_count > 300 and self.creation_date + datetime.timedelta(hours=12) < timezone.now():
      current = 300

    return current

  def mark_ready(self):
    self.status = self.__class__.PUBLISHED
    self.visibility = self.__class__.PUBLIC
    self.publish_date = timezone.now()

  def media_file_ext(self):
    return os.path.splitext(self.media_file.name)[1]

  def media_format_duration(self):
    seconds = int(self.duration % 60)
    minutes = int(self.duration / 60 % 60)
    hours = int(self.duration / 3600)
    format_str = ""
    if hours > 0:
      format_str = "{:02d}:{:02d}:{:02d}".format(hours, minutes, seconds)
    else:
      format_str = "{:02d}:{:02d}".format(minutes, seconds)
    return format_str

  def sorted_tags(self):
    return self.tags.all().order_by("name")

  def output_description(self):
    def inner_repl(match):
      hour = match.group(1)
      minute = match.group(2)
      second = match.group(3)
      duration = int(hour.strip(":")) * 3600 if hour else 0
      duration = duration + ((int(minute.strip(":")) * 60) if minute else 0)
      duration = duration + int(second.strip(":"))
      final = "<a href=\"{}?t={}\" data-seektime=\"{}\">{}</a>".format(self.get_absolute_url(), duration, duration, match.group(0))
      return final

    temp = re_timestamptext.sub(inner_repl, self.description).strip()
    return mark_safe(temp)


class MediaView(models.Model):
  visitor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
  logged_ip = models.GenericIPAddressField()
  media = models.ForeignKey(Media, on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now=True, db_index=True)
  updated_at = models.DateTimeField(auto_now=True)

  class Meta(object):
    verbose_name = "Media View"
    verbose_name_plural = "Media Views"
    """indexes = [
      models.Index(fields=['media', 'logged_ip', 'id'], name="Check Anon Media View"),
      models.Index(fields=['media', 'visitor', 'id'], name="Check Visitor Media View"),
    ]
    """


class MediaHistoryItem(models.Model):
  visitor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  media = models.ForeignKey(Media, on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now=True)
  updated_at = models.DateTimeField(auto_now=True, db_index=True)

  class Meta(object):
    verbose_name = "Media History Item"
    verbose_name_plural = "Media History Items"


class MediaPlaylist(models.Model):
  PUBLIC = 0
  PRIVATE = 1

  PRIVACY_STATE = (
    (PUBLIC, "Public"),
    (PRIVATE, "Private"),
  )

  owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  name = models.CharField(max_length=100)
  slug = models.SlugField()
  description = models.TextField(blank=True)
  media = models.ManyToManyField(Media)
  privacy = models.IntegerField(default=PUBLIC, choices=PRIVACY_STATE)
  created_at = models.DateTimeField(auto_now=True)
  updated_at = models.DateTimeField(auto_now=True)

  class Meta(object):
    verbose_name = "Media Playlist"
    verbose_name_plural = "Media Playlists"

  def __str__(self):
    return self.name

  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = slugify(self.title)[:50]

    self.updated_at = timezone.now()
    super().save(*args, **kwargs)

  def get_absolute_url(self):
    return reverse("videos:playlist", args=(self.slug,))


class MediaSubscription(models.Model):
  subscriber = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="subscriber")
  subbed = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="subbed")
  origin_media = models.ForeignKey(Media, on_delete=models.CASCADE, null=True)
  created_at = models.DateTimeField(auto_now=True)
  updated_at = models.DateTimeField(auto_now=True)

  class Meta(object):
    verbose_name = "Media Subscription"
    verbose_name_plural = "Media Subscriptions"

  def __str__(self):
    return "[{}] subbed to [{}]".format(self.subscriber, self.subbed)


class MediaFeaturedItem(models.Model):
  media = models.ForeignKey(Media, on_delete=models.CASCADE)

  class Meta(object):
    verbose_name = "Featured Media"
    verbose_name_plural = "Featured Media Items"
    ordering = ["-id"]

  def __str__(self):
    return self.media.title


class MediaReaction(models.Model):
  LIKE = 0
  DISLIKE = 1

  REACT_CHOICES = (
    (LIKE, "Like"),
    (DISLIKE, "Dislike"),
  )

  sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  media = models.ForeignKey(Media, on_delete=models.CASCADE)
  reaction = models.IntegerField(choices=REACT_CHOICES, db_index=True)
  date = models.DateTimeField(auto_now=True)

  def __str__(self):
    return str(self.id)

  class Meta(object):
    verbose_name = "Reaction"
    verbose_name_plural = "Reactions"
    unique_together = ("sender", "media", "reaction")

videos/forms.py
import os

from django.conf import settings
from django import forms
from django.urls import reverse
from django.core.validators import FileExtensionValidator

from resumable.fields import ResumableFileField
from resumable.widgets import ResumableFileInput

from haystack.forms import SearchForm

from .models import Media, MediaCategory


class TestMediaUploadForm(forms.ModelForm):
  
  media_file = ResumableFileField(
    chunks_dir=getattr(settings, "FILE_CHUNKS_UPLOAD_DIR"),
  )

  def __init__(self, *args, **kwargs):
    requser = kwargs.pop("user", None)
    super().__init__(*args, **kwargs)
    self.fields["media_file"].upload_url = reverse("videos:uploadchunk")
    if requser:
      base_chunks_dir = getattr(settings, "FILE_CHUNKS_UPLOAD_DIR")
      self.fields["media_file"].chunks_dir = os.path.join(base_chunks_dir, requser.username)
    else:
      raise Exception("No user instance passed to form")

    cats = MediaCategory.objects.all()
    choices = []
    for cat in cats:
      choices.append((cat.id, cat.title))

    self.fields["category"] = forms.ChoiceField(choices=choices, initial=1)

  def clean_category(self):
    data = self.cleaned_data["category"]
    category = MediaCategory.objects.filter(id=data).first()
    if not category:
      raise forms.ValidationError("MediaCategory with id={} does not exist".format(data))

    return category

  class Meta(object):
    model = Media
    fields = ["media_file", "title", "category", "rating", "description", "thumbnail", "tags"]


class SearchMediaForm(SearchForm):
  pass


class VideoOptions (forms.Form):
  autoplay = forms.BooleanField(initial=False)

videos/templates/videos/category.html
{% extends "videos/base.html" %}

{% load static %}
{% load bootstrap4 %}
{% load thumbnail %}
{% load humanize %}

{% block page_title %}Category: {{ category.title }}{% endblock %}

{% block extra_css %}

    <style>
      .media-item div a.title-link
      {
        color: #000000;
      }

      .media-item > div, .media-item div a {
        color: #555555;
      }

      .media-item .item-header img {
        width: 100%;
        height: auto;
      }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
      <div class="col">
        <h3>Category: {{ category.title }}</h3>
      </div>
    </div>

    <div class="row">
    {% for media in object_list %}
      <div class="col-md-4 mb-3 media-item">
        {% thumbnail media.thumbnail "350x200" as im %}
          <div class="item-header" style="position: relative;">
            <a href="{{ media.get_absolute_url }}">
              <img src="{{ im.url }}" alt="{{ media.title }}" width=350 height=200 class="d-block mb-2">
            </a>
            <div style="position: absolute; bottom: 4px; right: 8px; background-color: rgba(0, 0, 0, 0.75); color: #FFFFFF;" class="pl-1 pr-1">{{ media.media_format_duration }}</div>
          </div>
        {% endthumbnail %}
        <div class="title"><a href="{{ media.get_absolute_url }}" class="title-link">{{ media.title }}</a></div>
        <div class="channel-name">{{ media.uploader.username }}</div>
        <div class="media-extra">
          <span class="view-count">{{ media.view_count }} View{{ media.view_count|pluralize }}</span> • <span class="media-date"><time pubdate datetime="{{ media.publish_date|date:'c' }}" title="{{ media.publish_date|date:'N j, Y, P O' }}">{{ media.publish_date|naturaltime }}</time></span>
        </div>
        {% if user.is_staff %}
          <div class="media-admin-info">
            <a href="{% url 'videos:category' media.category.slug %}" title="{{ media.category.title }}">{{ media.category.title }}</a> | {{ media.get_rating_display }}
          </div>
        {% endif %}
     </div>
  {% endfor %}
    </div>

  {% if is_paginated %}
    <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a href="{% if page_obj.previous_page_number != 1 %}?page={{ page_obj.previous_page_number }}{% else %}{{ request.path }}{% endif %}" class="page-link">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }}</span></li>
      {% else %}
        <li class="page-item"><a href="{% if i != 1 %}?page={{ i }}{% else %}{{ request.path }}{% endif %}" class="page-link">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
    {% endif %}
    </ul>
  {% endif %}
{% endblock content %}

videos/templates/videos/channel.html
{% extends "videos/base.html" %}

{% load static %}
{% load bootstrap4 %}
{% load thumbnail %}
{% load humanize %}

{% block page_title %}Channel: {{ channel.username }}{% endblock %}

{% block extra_css %}

    <style>
      .media-item div a.title-link
      {
        color: #000000;
      }

      .media-item > div, .media-item div a {
        color: #555555;
      }

      .media-item .item-header img {
        width: 100%;
        height: auto;
      }
    </style>
{% endblock %}

{% block content %}
    <section class="mb-4 row channel-info">
        <div class="col-md-2">
        {% thumbnail channel.profile_image "100x100" as im %}
          <img src="{{ im.url }}" alt="{{ channel.username }} avatar" class="align-top">
        {% endthumbnail %}
        </div>
        <div class="col-md-5">
          <h3>Channel: {{ channel.username }}</h3>
          <div class="channel-meta">
            <span class="mr-3">Videos: {{ channel_media_count }}</span>
            <span class="mr-3">Subs: {{ channel_sub_count }}</span>
            <span class="mr-3">Views: {{ channel_view_count }}</span>
          </div>
        </div>
        <div class="col-md-5">
          <button class="btn subscribe{% if is_subbed %} active btn-secondary{% else %} btn-primary{% endif %}" data-channel-id="{{ sub.subbed.id }}" data-toggle-sub="{% url 'videos:togglesub' channel.id %}" data-num-subs="{{ channel_sub_count }}">Subscribe ({{ channel_sub_count }})</button>
        </div>
    </section>

    <div class="row">
      {% for media in channel_media %}
        <div class="col-md-4 mb-3 media-item">
          {% thumbnail media.thumbnail "350x200" as im %}
            <div class="item-header" style="position: relative;">
              <a href="{{ media.get_absolute_url }}">
                <img src="{{ im.url }}" alt="{{ media.title }}" width=350 height=200 class="d-block mb-2">
              </a>
              <div style="position: absolute; bottom: 4px; right: 8px; background-color: rgba(0, 0, 0, 0.75); color: #FFFFFF;" class="pl-1 pr-1">{{ media.media_format_duration }}</div>
            </div>
          {% endthumbnail %}
          <div class="title"><a href="{{ media.get_absolute_url }}" class="title-link">{{ media.title }}</a></div>
          <div class="channel-name">{{ media.uploader.username }}</div>
          <div class="media-extra">
            <span class="view-count">{{ media.view_count }} View{{ media.view_count|pluralize }}</span> • <span class="media-date"><time pubdate datetime="{{ media.publish_date|date:'c' }}" title="{{ media.publish_date|date:'N j, Y, P O' }}">{{ media.publish_date|naturaltime }}</time></span>
          </div>
          {% if user.is_staff %}
            <div class="media-admin-info">
              <a href="{% url 'videos:category' media.category.slug %}" title="{{ media.category.title }}">{{ media.category.title }}</a> | {{ media.get_rating_display }}
            </div>
          {% endif %}
       </div>
      {% endfor %}
    </div>

  {% if is_paginated %}
    <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a href="{% if page_obj.previous_page_number != 1 %}?page={{ page_obj.previous_page_number }}{% else %}{{ request.path }}{% endif %}" class="page-link">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }}</span></li>
      {% else %}
        <li class="page-item"><a href="{% if i != 1 %}?page={{ i }}{% else %}{{ request.path }}{% endif %}" class="page-link">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
    {% endif %}
    </ul>
  {% endif %}
{% endblock content %}

{% block extra_js %}
  <script type="text/javascript">
    $(".channel-info .subscribe").click(function(e) {
      e.preventDefault();
      var toggle_url = $(this).attr("data-toggle-sub");
      var sub_el = this;
      var active = $(this).hasClass("active");
      post_data = {
        "csrfmiddlewaretoken": "{{ csrf_token }}",
      };

      $.post(toggle_url, post_data, function(data) {
        var temp = parseInt($(sub_el).attr("data-num-subs"));
        temp = active == true ? temp - 1 : temp + 1;
        $(sub_el).text("Subscribe (" + temp + ")");
        $(sub_el).toggleClass("active").toggleClass("btn-primary")
          .toggleClass("btn-secondary");
      });
    });
  </script>
{% endblock %}

videos/templates/videos/featured.html
{% extends "videos/base.html" %}

{% load static %}
{% load thumbnail %}
{% load humanize %}
{% load videos_extras %}

{% block page_title %}Featured{% endblock %}

{% block extra_css %}
  <style>
      .media-item div a.title-link
      {
        color: #000000;
      }

      .media-item > div, .media-item div a {
        color: #555555;
      }

      .media-item .item-header img {
        width: 100%;
        height: auto;
      }
    </style>
{% endblock %}

{% block content %}

<section id="featured-media">
  <h3>Featured</h3>
  <div class="row">
    {% for item in object_list %}
      {% with media=item.media %}
        <div class="col-md-4 mb-3 media-item">
          {% thumbnail media.thumbnail "350x200" as im %}
            <div class="item-header" style="position: relative;">
              <a href="{{ media.get_absolute_url }}">
                <img src="{{ im.url }}" alt="{{ media.title }}" class="d-block mb-2">
              </a>
              <div style="position: absolute; bottom: 4px; right: 8px; background-color: rgba(0, 0, 0, 0.75); color: #FFFFFF;" class="pl-1 pr-1">{{ media.media_format_duration }}</div>
            </div>
          {% endthumbnail %}
          <div class="title"><a href="{{ media.get_absolute_url }}" class="title-link">{{ media.title }}</a></div>
          <div class="channel-name">{{ media.uploader.username }}</div>
          <div class="media-extra">
            <span class="view-count">{{ media.view_count }} View{{ media.view_count|pluralize }}</span> • <span class="media-date"><time pubdate datetime="{{ media.publish_date|date:'c' }}" title="{{ media.publish_date|date:'N j, Y, P O' }}">{{ media.publish_date|naturaltime }}</time></span>
          </div>
          {% if user.is_staff %}
            <div class="media-admin-info">
              <a href="{% url 'videos:category' media.category.slug %}" title="{{ media.category.title }}">{{ media.category.title }}</a> | {{ media.get_rating_display }}
            </div>
          {% endif %}
        </div>
      {% endwith %}
    {% endfor %}
  </div>

  {% if is_paginated %}
    <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a href="{% if page_obj.previous_page_number != 1 %}?page={{ page_obj.previous_page_number }}{% else %}{{ request.path }}{% endif %}" class="page-link">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }}</span></li>
      {% else %}
        <li class="page-item"><a href="{% if i != 1 %}?page={{ i }}{% else %}{{ request.path }}{% endif %}" class="page-link">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
    {% endif %}
    </ul>
  {% endif %}
</section>

{#{% latest_media %}#}
{% endblock content %}

videos/templates/videos/history.html
{% extends "videos/base.html" %}

{% load static %}
{% load bootstrap4 %}
{% load thumbnail %}
{% load humanize %}

{% block page_title %}Play History{% endblock %}

{% block extra_css %}

    <style>
      .media-item div a.title-link
      {
        color: #000000;
      }

      .media-item > div, .media-item div a {
        color: #555555;
      }

      .media-item .item-header img {
        width: 100%;
        height: auto;
      }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
      <div class="col">
        <h3>Play History</h3>
      </div>
    </div>

    <div class="row">
    {% for media in object_list %}
    {#{% with media=media_view.media %}#}
      <div class="col-md-4 mb-3 media-item">
        {% thumbnail media.thumbnail "350x200" as im %}
          <div class="item-header" style="position: relative;">
            <a href="{{ media.get_absolute_url }}">
              <img src="{{ im.url }}" alt="{{ media.title }}" width=350 height=200 class="d-block mb-2">
            </a>
            <div style="position: absolute; bottom: 4px; right: 8px; background-color: rgba(0, 0, 0, 0.75); color: #FFFFFF;" class="pl-1 pr-1">{{ media.media_format_duration }}</div>
          </div>
        {% endthumbnail %}
        <div class="title"><a href="{{ media.get_absolute_url }}" class="title-link">{{ media.title }}</a></div>
        <div class="channel-name">{{ media.uploader.username }}</div>
        <div class="media-extra">
          <span class="view-count">{{ media.view_count }} View{{ media.view_count|pluralize }}</span> • <span class="media-date"><time pubdate datetime="{{ media.publish_date|date:'c' }}" title="{{ media.publish_date|date:'N j, Y, P O' }}">{{ media.publish_date|naturaltime }}</time></span>
        </div>
        {% if user.is_staff %}
          <div class="media-admin-info">
            <a href="{% url 'videos:category' media.category.slug %}" title="{{ media.category.title }}">{{ media.category.title }}</a> | {{ media.get_rating_display }}
          </div>
        {% endif %}
     </div>
  {#{% endwith %}#}
  {% endfor %}
    </div>

  {% if is_paginated %}
    <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a href="{% if page_obj.previous_page_number != 1 %}?page={{ page_obj.previous_page_number }}{% else %}{{ request.path }}{% endif %}" class="page-link">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }}</span></li>
      {% else %}
        <li class="page-item"><a href="{% if i != 1 %}?page={{ i }}{% else %}{{ request.path }}{% endif %}" class="page-link">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
    {% endif %}
    </ul>
  {% endif %}
{% endblock content %}